### ISSUE TITLE
remove obfuscated code

### ISSUE THREAD

**Issue by ThomasWaldmann** [10se1ucgo/DisableWinTracking#110]
Such stuff just looks much too suspicious (see end of the code file).

**Comment by Ruined1** [comment]
@ThomasWaldmann can you maybe cite which file you're referring to and some line numbers?

**Comment by 10se1ucgo** [comment]
He's talking about the PowerShell command at the end. Just undo the Base64 encode and you'll see what it is. Stop being so paranoid.

**Comment by Ruined1** [comment]
@ThomasWaldmann the only thing I can imagine you're talking about is
>     if reinstall:
        # We encode in Base64 because the command is complex and I'm too lazy to escape everything.
        # It's uncoded format command: "Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode
        # -Register "$($_.InstallLocation)\AppXManifest.xml"}"
        encodedcommand = "RwBlAHQALQBBAHAAcAB4AFAAYQBjAGsAYQBnAGUAIAAtAEEAbABsAFUAcwBlAHIAcwB8ACAARgBvAHIAZQBhAGMA" \
                         "aAAgAHsAQQBkAGQALQBBAHAAcAB4AFAAYQBjAGsAYQBnAGUAIAAtAEQAaQBzAGEAYgBsAGUARABlAHYAZQBsAG8AcA" \
                         "BtAGUAbgB0AE0AbwBkAGUAIAAtAFIAZQBnAGkAcwB0AGUAcgAgACIAJAAoACQAXwAuAEkAbgBzAHQAYQBsAGwATABvA" \
                         "GMAYQB0AGkAbwBuACkAXABBAHAAcABYAE0AYQBuAGkAZgBlAHMAdAAuAHgAbQBsACIAfQA="

This is not "obfuscated", obfuscated would mean with the intention of preventing others from knowing what is does... If you read the comments above it you can very clearly see what it does, and if you're REALLY paranoid about it then you can decode it yourself using base64 (which is built right into python by the way)

The developer stated he did this because he didn't have time to piece the instructions together, and encoding was an easier way to deliver the payload of commands to powershell.

I'm closing this for now, if you were talking about something else let me know.

**Comment by ThomasWaldmann** [comment]
@10se1ucgo so you created a anti-spy / anti-tracking tool for windows and all you say about your obfuscated code is "stop being so paranoid". That's kind of ironic.

If the base64 encoding is just needed for more easily passing it into that call (?), then you could just have the clear text in your source code, then encode it at runtime using the base64 and then pass the computed result.

**Comment by Ruined1** [comment]
@ThomasWaldmann 
> ob·fus·cate
ˈäbfəˌskāt/Submit
verb
render obscure, unclear, or unintelligible.

There's clear writing defining what the **encoded**, *not* obfuscated, code does. It's open source, and anyone with a python interpreter (which are available for use online with no download) can decode it with two lines... importing base64 and using b64decode. You can even do it on one line if you like. This discussion is pointless, if the encoded data bothers you, don't use the program. It's that simple. My latest commits will be using base64 to transport a binary within our binary, so get used to it. Conversation closed.

**Comment by 10se1ucgo** [comment]
@ThomasWaldmann Clearly, you're misunderstanding. I'm fucking encoding it because there are too many quotes and shit to escape in the subprocess.call for me to be arsed to deal with. It's not ironic because it has nothing to do with spying and tracking. It's not like I can use PowerShell to spy on your computer. Lastly, I'm telling you how to check if its real. You want it fixed? Fucking do it yourself. I'm not wasting my time on stupid problems.

**Comment by 10se1ucgo** [comment]
@ThomasWaldmann Oh and if you're still concerned,

![:^)](http://i.imgur.com/sq2bKyN.png)
