### ISSUE TITLE
Will not run from a read-only directory.

### ISSUE THREAD

**Issue by batonac** [10se1ucgo/DisableWinTracking#112]
I've uploaded DisableWinTracking to a network file share so I can run it from multiple computers on the same LAN without re-downloading to each one.  When I connect using a username that has write access to the shared folder, the program runs successfully.  When I connect with read-only access, however, the program fails to run.

It seems that the program crashes if it can't write a log file to the directory it was executed from?

**Comment by Ruined1** [comment]
Yup, and this is likely by design of the developers of the logging module in python, on my network i always create one folder share that everyone has read, write, and execute permissions to, and put non-security risks (like DisableWinTracking) into said folder.

You gave me an idea though,i may implement some unique identifier just in the log name for people that are using it over a network share so there's a log for each pc

**Comment by batonac** [comment]
Okay thanks, I'll follow your advice.

**Comment by 10se1ucgo** [comment]
It's not by design, I just need a proper try/except block :P

**Comment by 10se1ucgo** [comment]
Fixed.

**Comment by batonac** [comment]
Hey wow, thanks!  Now when do we get a new build? ;-)

**Comment by 10se1ucgo** [comment]
Soon, just gotta inspect/clean some of the newer commits.

**Comment by Ruined1** [comment]
@10se1ucgo well, it's not by design if you want the program to run without producing a log, that way people can complain to you about why "it didn't work" in a million issues reports without ever being able to provide you with a log :wink: I suggest leaving it the way it is and have network users do what I said above
