### ISSUE TITLE
MS+NSA tracking renamed to "Connect User Experience and Telemetry service"

### ISSUE THREAD

**Issue by HLFH** [10se1ucgo/DisableWinTracking#124]
Hi,

As [we can see here](http://www.lifehacker.com.au/2015/11/how-to-disable-microsofts-new-spying-service-on-windows-10/), after the November update, MS+NSA tracking have been renamed to `Connect User Experience and Telemetry service`. Does it imply changes for DisableWinTracking?

**Comment by W4RH4WK** [comment]
@10se1ucgo probably wants to adapt following line:

```python
    disableservice('Diagnostics Tracking Service')
```

Older stuff might still work since they mainly changed the display name (and re-enabled some settings). The original service handle is still the same `DiagTrack`

![image](https://cloud.githubusercontent.com/assets/328798/11500130/65630726-982b-11e5-80f4-4ed8a29a04bd.png)

**Comment by 10se1ucgo** [comment]
Fixed
