### ISSUE TITLE
The best way to block tracking and privacy invasion.

### ISSUE THREAD

**Issue by ghost** [10se1ucgo/DisableWinTracking#180]
**Why Microsoft want user data?**
- For selling it to 3rd party companies
- Tracking user activity for better Ad delivery
- And make huge bucks out of it.

**Best way to defend.**
- It is impossible to block data collection. Even after using this tool, I could see data being sent to Microsoft servers. For Microsoft, the little data is valuable. They can still make money from it.
- The best way is to contaminate the data they are collecting. The same principle has been used in many fields. Companies contaminate ethyl alcohol with methyl alcohol, rendering it useless. Yes, people can easily access the alcohol, but they cannot drink it.
- The same should be done here. There should be an option to actively transfer false random data to Microsoft servers, in a way that whatever data they collect is rendered useless. If enough people do it, they will be forced to shut down the program because companies won't be interested in buying useless data.

**Next step:**
- Implement data contamination protocol.
- Get some experts to contribute.
- Spread the word through social media and tech magazines.

**Comment by DVLP** [comment]
As the guy in this video https://www.youtube.com/watch?v=u1kGMCfb2xw says
use Spybot Anti-Beacon to block outgoing traffic. https://forums.spybot.info/downloads.php?id=55

Can you confirm if this stops you seeing that traffic you wrote about?

**Comment by VitaminX4** [comment]
I can't do the tests since I'm travelling now, but will do it once I return home. But the Spybot website did say that Anti-Beacon blocks "any known tracking features included by Microsoft in the operating system". That is the concerning part. Like @Barnacules mentioned in a earlier video how Microsoft pushes update packages into the PC, it is easy for them to bypass everything we throw at it.


Its good to know that many people are tackling the problem. But I still believe having an option to contaminate data, and have it actively transferred to Microsoft, by enough people is more than enough to send a message. 


This reminds me of an app developed by Chainfire, called Pry-Fi. Instead of blocking the vulnerability in our device, he actually used it to go offensive on the attacker/surveillance system.

http://forum.xda-developers.com/showthread.php?t=2631512  


We have to go offensive n these people. Show em what a few people are capable of. :)

**Comment by neuhaus** [comment]
I think a program to contaminate the data should be a separate project

**Comment by VitaminX4** [comment]
That  decision is up to you, developers. I would totally love to use such a tool. Many people will
