### ISSUE TITLE
Port to C#

### ISSUE THREAD

**Issue by 10se1ucgo** [10se1ucgo/DisableWinTracking#186]
For the sake of my sanity, I plan to port DWT to C#. It'll make it much easier to distribute, as playing around with redist packages and pyinstaller is not fun at all.

**Comment by BlockWorksDigitalDevelopment** [comment]
Nice

**Comment by 10se1ucgo** [comment]
Started work on GUI, here's a preview
![GUI Preview](http://i.imgur.com/J2TutYu.png)

**Comment by 10se1ucgo** [comment]
Might need to restart, forgot that UWP apps are required to be downloaded from the store :( Goodbye, pretty Metro UI.

**Comment by u55** [comment]
:-1:  But python is 1000 times easier to read than C#, which is very important for garnering user trust with this sort of potentially-insecure open-source app.

**Comment by 10se1ucgo** [comment]
And C# is 1000 times easier to distribute. I'm not going to make it harder on myself just because some users are paranoid and can't learn how to read an easy language. It's not C.

**Comment by 10se1ucgo** [comment]
Well, it's not as pretty as it used to be, but I tried my hardest. Let me know if you guys want something else.
![](http://i.imgur.com/orxqjy6.png)

**Comment by u55** [comment]
@10se1ucgo 

>...can't learn how to read an easy language. It's not C, learn. 

If you don't want advice or help from the community, that's your prerogative. No need for insults. This is github, not youtube; we are all here to share and help.

I can read C# and C, that's not the point. The point is that: (1) a verbose language, like C/C++/C#/java/etc., is not the best suited for small security-critical apps whose source code should be clear, concise, and easy to verify what they actually do, and (2) a compiled language on Windows makes it much more difficult for users who don't want to have to trust that the supplied executable contains the same computer instructions as the source code they are reading online. Interpreted scripting languages, like Python/Perl/Ruby/Batch-files/etc., make it easy for users like myself to use the source code directly.

> I'm not going to make it harder on myself just because some paranoid users don't trust...

Also, I find it surprising that you are not interested in transparency for paranoid users since *all* of your potential users are paranoid about security, that's why they are interested in your app in the first place!

There are numerous [other tools available on the internet](http://www.ghacks.net/2015/08/14/comparison-of-windows-10-privacy-tools/) that perform similar modifications to Windows 10, but most of them are not open source. Chances are, a large number of people using your app choose it precisely because it contains a few lines of open source code that are easy to verify.

> And C# is 1000 times easier to distribute.

But not for people who are unwilling to blindly trust an executable downloaded from the internet. However, for people who don't have python installed on their system and want a simple executable, PyInstaller is not the only option. Have you tried cx_Freeze, py2exe, or bbFreeze?  No one is asking you to make it harder on yourself. Quite the contrary, if you are unhappy with PyInstaller, it may be much easier to replace PyInstaller with cx_Freeze, for instance, than to completely port the entire source code tree to another language. This is where the community can offer suggestions, help, or even pull requests. But no one is going to be eager to help if all you have to offer are insults.

**Comment by Didey** [comment]
@u55 he certainly didn't insult you, but I will, retard. You're getting upset because the maintainer of an OPEN SOURCE project wants to change the code. Got a problem with that? Fork the repo. Don't waste time complaining about nonsense.

**Comment by 10se1ucgo** [comment]
> (1) a verbose language, like C/C++/C#/java/etc., is not the best suited for small security-critical apps whose source code should be clear, concise, and easy to verify what they actually do

It's not verbose at all, I'm not sure what you're talking about. Also, the code is actually much more clear, as I can move GUI code to a XAML file and have all the actual code in a few files.

> a compiled language on Windows makes it much more difficult for users who don't want to have to trust that the supplied executable contains the same computer instructions as the source code they are reading online.

ILSpy / JetBrains dotPeek will convert IL code to C#. You can verify the source code that way,  just like you can use pyinstxtractor + uncompyle2.

> Interpreted scripting languages, like Python/Perl/Ruby/Batch-files/etc., make it easy for users like myself to use the source code directly.

Use source code directly for Python:

1. Install Python 2.7
2. Install `pip`
3. Run `pip install pypiwin32`
4. Run `pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix`
5. Run `git clone https://github.com/10se1ucgo/DisableWinTracking/`
6. Run `cd DisableWinTracking`
7. Run `python dwt.py`

Use source code directly for C#

1. Install Visual Studio 2015 Community Edition
2. Run `git clone https://github.com/10se1ucgo/DisableWinTracking/`
3. Open `DisableWinTracking.sln` in VS.
4. Press the `Start` button.

> Chances are, a large number of people using your app choose it precisely because it contains a few lines of open source code that are easy to verify.

C# version will also be a few lines of source code. Likely, shorter than Python, as the APIs for Windows things are better. A majority of the Python source code is GUI code, which won't be present in C# (XAML file)

> Have you tried cx_Freeze, py2exe, or bbFreeze? No one is asking you to make it harder on yourself. Quite the contrary, if you are unhappy with PyInstaller, it may be much easier to replace PyInstaller with cx_Freeze

Yes. I have. PyInstaller is the most up-to-date of all three, and works better. I have no issue with PyInstaller, but the process itself is quite time consuming, for all of these.

> This is where the community can offer suggestions, help, or even pull requests.

I haven't had a pull-request with a significant amount code since @Ruined1 stopped working on the project.

> But no one is going to be eager to help if all you have to offer are insults.

I didn't insult you.

**Comment by u55** [comment]
@10se1ucgo 

> I didn't insult you.

Okay. I'll take your word for it. I interpreted "can't learn how to read an easy language" as an insult. Thanks for clearing that up. 

> Also, the code is actually much more clear

If you think you can maintain readability for casual users while porting to C#, then more power to you. This has *not* been my experience with C#, either writing or reading other people's code. I find C# to be a very verbose language.

> ILSpy / JetBrains dotPeek will convert IL code to C#.

I am sure it is possible, but this sort of hassle would heavily discourage me from ever trying out something I just found randomly on the internet. I can't speak for everyone, so maybe that's just me.

> I haven't had a pull-request with a significant amount code since @Ruined1 stopped working on the project.

Well, normally I might be interested in contributing, it sounds like a fun project, but, just in today's interaction, I have found that the DisableWinTracking user community is a little too hostile for my taste.

Best of luck to you.

**Comment by Didey** [comment]
@u55 you think the "casual users" would be concerned with the readability of the code? Most programmers don't care to read the source of much of the software they use. Even so, I personally find C# much easier to read because it doesn't take whitespace into account when compiling, but that's me. Think otherwise? Fork.

**Comment by 10se1ucgo** [comment]
> Well, normally I might be interested in contributing, it sounds like a fun project, but, just in today's interaction, I have found that the DisableWinTracking user community is a little too hostile for my taste.

Pathetic excuse, but good for you.

**Comment by rgl** [comment]
You should make it a CLI application. If you really want a GUI application, make it call the CLI one or call into a shared library between the two.

**Comment by 10se1ucgo** [comment]
It's not about what "I" want. I want to never develop this garbage again, but I have users to cater to.

**Comment by Daniil1288** [comment]
@10se1ucgo, I feel you, and you're pretty much the last person actively developing something that might disable windows 10 tracking (afaik), so, good luck!

**Comment by kevmt** [comment]
Haha! When i saw python, i said here we go again.. but i am happy with the change.. compiled or not i will run it than talk about the source code.. all i care is my privacy & to make windows 10 smooth. Using vscode + wampp w/ 12Gb ram i5 windows 10 still feels slow.. so go figure.

**Comment by Ruined1** [comment]
@10se1ucgo if you ever see this, did you continue the C# or abandon the project all together?

**Comment by Didey** [comment]
@Ruined1 I let him know, and if he doesn't want to continue the project, I'll do it.

**Comment by Ruined1** [comment]
@Didey I am continuing the project, or at least trying to. I'm a collaborator because of how much I've contributed to the project in the past, which gives me access to everything we need to move forward. I'm just curious if @10se1ucgo is still interested in pursuing this project because if he's working on a C# port in the background then I don't want to continue working on the python source when I could be contributing to that. I'll continue to do bug fixes, and feel free to submit pull-requests (I'll review and accept them), but I'm going to hold off on any major enhancements until I know for sure.

**Comment by Didey** [comment]
@Ruined1, he's not working on a C# port. He's a close friend, and I told him I'd maintain if he didn't want to. No idea why he's not replying to this thread, probably will later today.

**Comment by Ruined1** [comment]
@Didey Ah, ok, understood. If he turns it over I will go ahead and continue collaborating with you. Trying to patch the couple issues currently being experienced by users and put out a new release. I will go ahead and close this then since it isn't happening.

**Comment by Svetomech** [comment]
@10se1ucgo why the sudden mood swing? Deciding to port the project to C# and then deciding not to... Makes me curious, what's the reason behind this decision?

**Comment by 10se1ucgo** [comment]
uhh idk I haven't been doing much regarding my GitHub projects primarily because ~~im lazy~~ school. I think I've gotten over my "'c# xdd" phase

I'll give the codebase a cleanup sometime this week and see if we can't restore this baby back to glory
