### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by Mrsevic** [10se1ucgo/DisableWinTracking#20]
After running the delete functionality search functionality is not working anymore.

**Comment by TheDrink** [comment]
Can you please go into more detail as to what is wrong so I can fix the code?

**Comment by KoalaBear84** [comment]
I've had the same problem. But I think it is not related to DisableWinTracking.

I always disable "Windows Search" service. Looks like since Windows 10 it is ALSO used by the Start Menu.......... Bummer. So if you enable this again, the start menu search will work. Unfortunately "SearchIndexe.exe" will be running again. I don't need my files to be indexed as I use "Everything" for that purpose..

**Comment by 10se1ucgo** [comment]
Search works for me.
