### ISSUE TITLE
Start menu search "threshold.appcache" is still being allowed

### ISSUE THREAD

**Issue by ultramancool** [10se1ucgo/DisableWinTracking#21]
This sends a wealth of potential tracking info including a unqiue machine identifier. This occurs every time you search on the start menu, even with all privacy options set and DisableWinTracking run.

https://up1.ca/#Dpl7PlGX6DHUqQ8B9p9oAQ

**Comment by seatsea** [comment]
Could it be because of this setting? https://up1.ca/#4jZxBPIBqpM83AHhkBhFLQ

**Comment by ultramancool** [comment]
I have this turned completely off and disabled via GPO too. Note that it doesn't send the search query but does send a whole bunch of other identifying info. 

https://up1.ca/#roAfNVbXnO9gFGygm6iKRQ

I brought this problem up a few days ago on Hacker News, now Ars Technica is also reporting that Windows fails to obey this setting. 

http://arstechnica.co.uk/information-technology/2015/08/even-when-told-not-to-windows-10-just-cant-stop-talking-to-microsoft/

Maybe a hosts file block for www.bing.com would be the only solution...

**Comment by ZachR0** [comment]
Any updates on this? This is pretty unsettling.

**Comment by thenoncoder** [comment]
I've edited my hosts file, disabled all the privacy-invading services, unchecked all the stuff I could uncheck in the settings app, and ran all sorts of batch files. Do I still need to run this app?
I mean, I haven't done anything in regards to the registry, so, maybe it's better than manually going through all the registry keys.

**Comment by 10se1ucgo** [comment]
@thenoncoder this is the wrong place to be asking that. If you already did everything then you don't need to, unless you want to just in case.

**Comment by thenoncoder** [comment]
Does the app modify registry keys?
I tried it, and I'm not sure if it doe that.
I want to be sure all the telemetry crap is out of my pc.

**Comment by 10se1ucgo** [comment]
Yes it does

**Comment by thenoncoder** [comment]
Good.
A couple more batch files and I should be good.

**Comment by Ruined1** [comment]
SearchUI.exe is located at C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy

I am currently creating a way to remove some system apps (yes, even the ones that shouldn't be able to) thanks to participation in https://github.com/10se1ucgo/DisableWinTracking/issues/48

I know your issue was opened first, but as important information was discussed in the above issue, and this one has gone off topic, I will go ahead and close as duplicate. Please feel free to contribute in https://github.com/10se1ucgo/DisableWinTracking/issues/48
