### ISSUE TITLE
Error: UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 9: invalid continuation byte Failed to execute script dwt

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [10se1ucgo/DisableWinTracking#377]
**INFORMATION:**

* Windows Edition: Enterprize LTSB 1607
* Architecture : 64bit

Error at starting program, before window.

**LOG:**
```
Traceback (most recent call last):
  File "dwt.py", line 496, in <module>
  File "dwt.py", line 94, in __init__
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 9: invalid continuation byte
Failed to execute script dwt
```

**Comment by Ruined1** [comment]
Line 496 calls into __init__
Line 94 (inside __init__) simply sets the icon for the executable

This should work universally across all windows platforms, and I'm unable to reproduce it. What are your language and region settings on this machine? I'm willing to bet you're using some Cyrillic language?

If that's the case then, unfortunately, nothing can be done about it because this would be an issue with wxPython, not DWT. Try running it from the root drive. I.E. C:\DisableWinTracking.exe

**Comment by Dmitrij-Polyanin** [comment]
Yes, cyrillic - russian.
It works on C:\DisableWinTracking.exe, thanks!

**Comment by Ruined1** [comment]
@Dmitrij-Polyanin I will write that solution on the documentation. Thank you for contributing!

**Comment by Ruined1** [comment]
![Imgur](https://i.imgur.com/q4aBqeu.png)

**Comment by piotr-yuxuan** [comment]
Hiya there, just a further report: it doesn't work either when its path contains characters like `é`, `è`, `à`.
