### ISSUE TITLE
can you share explanation for each option 

### ISSUE THREAD

**Issue by Sandy4321** [10se1ucgo/DisableWinTracking#420]
can you share explanation for each option 
**INFORMATION:**

* Windows Edition (Home):
* Architecture (64bit):
* Options used:

**LOG:**

```python
REPLACE THIS WITH DWT.LOG
```

**Comment by Ruined1** [comment]
Hovering over each options provides an explanation. Most of them are self-explanatory. If you don't know what this program is doing, it's likely not something you want to run. There are warnings for the most inhibiting options. An example is below:
![image](https://user-images.githubusercontent.com/1514573/55630255-41ee9d80-5783-11e9-8189-ce0ea778cb8e.png)

Otherwise, it's open source for a reason :)

**Comment by Sandy4321** [comment]
thanks great code
