### ISSUE TITLE
Xbox party chat connection issues

### ISSUE THREAD

**Issue by MegaMech** [10se1ucgo/DisableWinTracking#457]
Hello,

I tried reverting all of the IP/domain blocking features to see if that was issue. I feel like the IP blocking thing is preventing voice chat connections. Discord and other services work, just not the microsoft one. I have a laptop that party chat works fine on. This W10 install is pretty fresh. Xbox chat works like garbo anyway, so it just be some kinda bug.
After reverting I was able to connect with an xbox player, as soon as another PC player joined I just couldn't hear them. 

Do you have any suggestions for making sure the xbox services are not blocked? I know how to check hosts file, is that a good start?

W10 Pro

Thx

**Comment by DeeJayhX** [comment]
There are warnings that pop up and warn you that you risk breaking microsoft services using this software. Since this software runs once and can't sniff your traffic out to determine what is telemetry and what is valid data 24/7 (especially given the majority of that data is encrypted) the only way to stop the telemetry and privacy breaches are to block the servers which telemetry and other tools report back to. It just so happens that server might also handle game licensing/DRM, or Xbox Voice Chat.

Here is a default `hosts` file:
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```

Copy and paste that into your hosts file with a notepad that is run as administrator. If that doesn't work try running DisableWinTracking in revert. Good luck.
