### ISSUE TITLE
We forked DWT, so it can live on! Please reference our fork in the readme!

### ISSUE THREAD

**Issue by bitlog2** [10se1ucgo/DisableWinTracking#467]
We forked DWT here:
https://github.com/bitlog2/DisableWinTracking

Could you link to us in the readme?

We like DWT and want to build a community of maintainers to keep it alive!

**Comment by DeeJayhX** [comment]
@bitlog2 Sure, I'll add that for people seeking an alternative. Feel free to add me as a collaborator on that project if you would like and I may pop in and help solve issues from time to time. I contributed about a fifth of the overall development to the original project.
![image](https://user-images.githubusercontent.com/1514573/106395097-41da7b80-63b5-11eb-8b2a-02c18a10d4f2.png)

**Comment by 10se1ucgo** [comment]
Hi to anyone reading this, I think its about time I awaken from my slumber. 

DWT was a tiny little script I wrote in the summer between middle school and high school as a very young and naïve kid, but soon since I quickly lost both interest and time and moved onto other projects. Not to mention, at some point I stopped caring much about the issue or even the ability of DWT to mitigate the issue. While I certainly regret my lack of correspondence on the matter, I appreciate all the work done both by the community and my excellent de-facto maintainer @DeeJayhX in my absence. 

I'll be pinning this issue and switching the DWT archive to archival mode shortly, and I wish you all the best of luck in your continued efforts.
