### ISSUE TITLE
[Idea] Clean removal of system apps (bypass error 0x80073CFA)

### ISSUE THREAD

**Issue by leonghui** [10se1ucgo/DisableWinTracking#48]
Hi,

I would like to share my findings. The error 0x80073CFA can be bypassed by toggling the "IsInbox" column for the system package in the Package table in %ProgramData%\Microsoft\Windows\AppRepository\StateRepository-Machine.srd. It is an SQLite database that can be viewed and edited with any SQLite tool after stopping the StateRepository service and taking over the file ownership.

I managed to remove Microsoft Edge from the Start menu using Remove-AppxPackage afterwards, but there were no changes to the package list exported from the install_wim_tweak tool (http://www.msfn.org/board/topic/152688-win6x-registry-tweak/) so further cleanup maybe necessary.

Best of luck.

```
Remove-AppxPackage : Deployment failed with HRESULT: 0x80073CFA, Removal failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CFA)
error 0x80070032: AppX Deployment Remove operation on package xxx from:
xxx failed. This app is part of Windows and cannot be uninstalled on a per-user basis. An administrator can attempt to remove the app from the computer using Turn Windows Features on or off. However, it may not be possible to uninstall the app.
```

**Comment by leonghui** [comment]
Some steps and screenshots:
1. Try removing the system package using **Remove-AppxPackage**
![before](https://cloud.githubusercontent.com/assets/6092315/9498120/ca8d62b8-4c4a-11e5-9067-57d1005daec5.PNG)

2. Run **cmd** as SYSTEM using **PsExec** (https://technet.microsoft.com/en-us/sysinternals/bb897553.aspx)
3. Copy *%ProgramData%\Microsoft\Windows\AppRepository\StateRepository-Machine.srd* to the Desktop (**do make a backup**)

4. Toggle ***IsInbox*** to 0
![Find the package under PackageFullName](https://cloud.githubusercontent.com/assets/6092315/9498071/95637df2-4c4a-11e5-91a6-2bada161cd37.PNG)
![Change IsInbox from 1 to 0](https://cloud.githubusercontent.com/assets/6092315/9498076/9943837c-4c4a-11e5-8fea-e90f2e84d5c0.PNG)

5. Kill **sihost.exe** and the **svchost.exe** instance that shares the same PID as the **StateRepository** service (cannot be stopped via usual methods)
6. Ignore the warning window, note that Start Menu will not work until reboot
![Ignore this](https://cloud.githubusercontent.com/assets/6092315/9498110/b7d8f09c-4c4a-11e5-95b0-ae09dd231dd8.PNG)

7. Delete *%ProgramData%\Microsoft\Windows\AppRepository\StateRepository-Machine.** (including the SQLite temp files). This would not work until step 5 is done properly.
8. Copy the edited **StateRepository-Machine.srd** to *%ProgramData%\Microsoft\Windows\AppRepository\*
9. Restart the **StateRepository** service and try removing the system package again
![Success](https://cloud.githubusercontent.com/assets/6092315/9498140/dffb43f4-4c4a-11e5-9263-a9370a9e7623.PNG)

10. Reboot to restore the Start Menu

**Comment by 10se1ucgo** [comment]
Not sure how I'd do this programmatically. Any recommendations?

**Comment by Ruined1** [comment]
Assign this one to me, I'll do it.

**Comment by 10se1ucgo** [comment]
@Ruined1 Added you as a collaborator and assigned you to the issue. Thanks for your work :)

**Comment by Ruined1** [comment]
It's an honor.

**Comment by Ruined1** [comment]
@leonghui It can't be encrypted if you're able to access it, so it must not be sqlite?

```
>>> import sqlite3
>>> conn = sqlite3.connect('StateRepository-Machine.srd')
>>> c = conn.cursor()
>>> c.execute ('SELECT * FROM IsInbox')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.DatabaseError: file is encrypted or is not a database
```

**Comment by thenoncoder** [comment]
What's the progess so far on this?

**Comment by Ruined1** [comment]
It's currently in developement, there is no ETA. I am working diligently on this, but I don't make money writing code, so it gets done between work and sleep :sweat_smile:

**Comment by thenoncoder** [comment]
Okay. Thanks a lot for removing Windows 10 tracking for us.

There are a couple of batch files on the /r/windows10 subrddit on *Reddit*, so you might want to add them to your app, just to make sure that the tracking is fully gone. The subreddit also has people who have posted the various services that need to be disabled and other stuff like that, but I'm sure that you've already added those, as I've used the app and they were there.

One more thing, two small questions.

If I disable the services rather than delete them is there **ANY** kind of possibility for them to be enabled by *Microsoft* again, without me knowing it?

And, if I just delete them, will that cause problems to my system? I don't think so, but I still want to be sure.

**Comment by Ruined1** [comment]
> There are a couple of batch files on the /r/windows10 subrddit on Reddit

I'll keep that in mind.

> If I disable the services rather than delete them is there ANY kind of possibility for them to be enabled by Microsoft again, without me knowing it?

Absolutely, with any windows update and (who knows) at any time they like if they've left such ability in their operating system. It's closed source, so who knows? To assume that far is borderline paranoia, but times are strange...

> And, if I just delete them, will that cause problems to my system? I don't think so, but I still want to be sure.

We eat what we cook, @10se1ucgo and I both use this and haven't experienced any issues. I use the DELETE option on my computers.

**Comment by thenoncoder** [comment]
I guess the only way to be fully sure is if someone makes a live CD especially for this.

**Comment by W4RH4WK** [comment]
Wow, it's nice to see that there is a way to remove those packages with some workaround using the `Remove-AppxPackage` commandlet. Does the removal work in a clean way?
The way I did it was using the `dism.exe` tool. (https://github.com/W4RH4WK/Debloat-Windows-10/blob/47c2666ddd162a511a6517d74502d3dc8465a430/scripts/remove-default-apps.ps1#L64-L98)

**Comment by Ruined1** [comment]
@10se1ucgo I still need to know which ones you want to be able to remove, there are certain one I would think it unwise to allow removal of. Here is a list:

> Microsoft.Windows.CloudExperienceHost_10.0.10240.16384_neutral_neutral_cw5n1h2txyewy|1
Microsoft.AAD.BrokerPlugin_1000.10240.16384.0_neutral_neutral_cw5n1h2txyewy|1
Microsoft.AccountsControl_10.0.10240.16384_neutral__cw5n1h2txyewy|1
Microsoft.BioEnrollment_10.0.10240.16384_neutral__cw5n1h2txyewy|1
Microsoft.LockApp_10.0.10240.16384_neutral__cw5n1h2txyewy|1
Microsoft.MicrosoftEdge_20.10240.16384.0_neutral__8wekyb3d8bbwe|1
Microsoft.Windows.ContentDeliveryManager_10.0.10240.16384_neutral_neutral_cw5n1h2txyewy|1
Microsoft.Windows.ParentalControls_1000.10240.16384.0_neutral_neutral_cw5n1h2txyewy|1
Microsoft.Windows.ShellExperienceHost_10.0.10240.16384_neutral_neutral_cw5n1h2txyewy|1
Microsoft.XboxGameCallableUI_1000.10240.16384.0_neutral_neutral_cw5n1h2txyewy|1
Microsoft.XboxIdentityProvider_1000.10240.16384.0_neutral_neutral_cw5n1h2txyewy|1
Windows.ContactSupport_10.0.10240.16384_neutral_neutral_cw5n1h2txyewy|1
windows.immersivecontrolpanel_6.2.0.0_neutral_neutral_cw5n1h2txyewy|1
Windows.MiracastView_6.3.0.0_neutral_neutral_cw5n1h2txyewy|1
Windows.PrintDialog_6.2.0.0_neutral_neutral_cw5n1h2txyewy|1
Windows.PurchaseDialog_6.2.0.0_neutral_neutral_cw5n1h2txyewy|1
windows.devicesflow_6.2.0.0_neutral_neutral_cw5n1h2txyewy|1
Microsoft.WindowsFeedback_10.0.10240.16393_neutral_neutral_cw5n1h2txyewy|1
Microsoft.Windows.Cortana_1.4.8.176_neutral_neutral_cw5n1h2txyewy|1

**Comment by 10se1ucgo** [comment]
* WindowsFeedback
* MicrosoftEdge
* ContactSupport
* CloudExperienceHost
* ParentalControls
* Xbox[GameCallableUI/IdentityProvider]
* Cortana

**Comment by Ruined1** [comment]
@10se1ucgo going to start working on this today, had a busy week :sleepy:

**Comment by Draxler** [comment]
Great work you guys doing.
Thaks again to all devs and contributors to this project. :+1:

**Comment by intika** [comment]
Thanks a million !!!!!!!

**Comment by duaneking** [comment]
Any updates?

**Comment by Fifteen15Studios** [comment]
I found this Powershell script somewhere, edited it slightly:

`function Enable-Privilege {  
  param($Privilege)
  $Definition = @'
using System;  
using System.Runtime.InteropServices;  
public class AdjPriv {  
  [DllImport("advapi32.dll", ExactSpelling = true, SetLastError = true)]
  internal static extern bool AdjustTokenPrivileges(IntPtr htok, bool disall,
    ref TokPriv1Luid newst, int len, IntPtr prev, IntPtr rele);
  [DllImport("advapi32.dll", ExactSpelling = true, SetLastError = true)]
  internal static extern bool OpenProcessToken(IntPtr h, int acc, ref IntPtr phtok);
  [DllImport("advapi32.dll", SetLastError = true)]
  internal static extern bool LookupPrivilegeValue(string host, string name,
    ref long pluid);
  [StructLayout(LayoutKind.Sequential, Pack = 1)]
  internal struct TokPriv1Luid {
    public int Count;
    public long Luid;
    public int Attr;
  }
  internal const int SE_PRIVILEGE_ENABLED = 0x00000002;
  internal const int TOKEN_QUERY = 0x00000008;
  internal const int TOKEN_ADJUST_PRIVILEGES = 0x00000020;
  public static bool EnablePrivilege(long processHandle, string privilege) {
    bool retVal;
    TokPriv1Luid tp;
    IntPtr hproc = new IntPtr(processHandle);
    IntPtr htok = IntPtr.Zero;
    retVal = OpenProcessToken(hproc, TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY,
      ref htok);
    tp.Count = 1;
    tp.Luid = 0;
    tp.Attr = SE_PRIVILEGE_ENABLED;
    retVal = LookupPrivilegeValue(null, privilege, ref tp.Luid);
    retVal = AdjustTokenPrivileges(htok, false, ref tp, 0, IntPtr.Zero,
      IntPtr.Zero);
    return retVal;
  }
}
'@  
  $ProcessHandle = (Get-Process -id $pid).Handle
  $type = Add-Type $definition -PassThru
  $type[0]::EnablePrivilege($processHandle, $Privilege)
}

function Take-Over($path) {  
  $owner = [Security.Principal.NTAccount]'Administrators'

  $key = [Microsoft.Win32.Registry]::LocalMachine.OpenSubKey($path, 'ReadWriteSubTree', 'TakeOwnership')
  $acl = $key.GetAccessControl()
  $acl.SetOwner($owner)
  $key.SetAccessControl($acl)

  $acl = $key.getaccesscontrol()
  $rule = New-Object System.Security.AccessControl.RegistryAccessRule "Administrators", "FullControl", "ContainerInherit", "None", "Allow"
  $acl.SetAccessRule($rule)
  $key.SetAccessControl($acl)
}

do {} until (Enable-Privilege SeTakeOwnershipPrivilege)

function Remove-Package($name) {  
  $key = "SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages\$name"
  Take-Over $key
  Remove-Item -Path HKLM:"$key\Owners" -Force -Recurse
  & C:\Windows\System32\PkgMgr.exe /up:$name /norestart /quiet
}

# Remove Feedback
$packageBase = "Microsoft-WindowsFeedback"
$packageNames = (dir ("HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages\" + $packageBase + "*")).name

forEach ($package in $packageNames)
{   
    Remove-Package $package.substring($package.indexOf($packageBase))
}`

You can change `$packageBase` to different package names. I changed the script slightly from its original state because the original only worked on very specific versions of the packages, whereas this will work with any version. it gets the whole package identifier (including version number) from the registry.

Verified working with "Feedback" (Microsoft-WindowsFeedback) and "Contact Support" (Microsoft-Windows-ContactSupport). I tried with "Cortana" (Microsoft-Windows-Cortana) but it didn't seem to work fully. I think Cortana has other hooks into the OS. Haven't tried any of the others listed by @10se1ucgo

**Comment by elimn** [comment]
Thank you for sharing the script @Fifteen15Studios. This was the top result on Google for uninstalling Cortana. I tried removing Cortana with it. After a reboot the application was indeed missing and the start menu worked. However, the keyboard search in the Start Menu was completely disabled. The Search Windows box still appears, but typing in it does nothing. 

For anyone using your script: You probably do not want to remove Cortana, unless you never type in the Search Windows box nor Start Menu. If you use a replacement Start Menu application then this caveat probably does not apply to you.

**Comment by Suncatcher** [comment]
The variable `$packageNames` is always empty for me. What's the matter?

**Comment by ijry** [comment]
does anyone know remove   AppX packages installed for a user that doesn't exists!

**Comment by ijry** [comment]
not work for me 
https://social.technet.microsoft.com/Forums/windows/en-US/5e7c8439-bf9a-4050-8fbd-b2c207eb7b52/how-to-delete-an-app-from-a-deleted-users-account?forum=win10itprogeneral&prof=required
