### ISSUE TITLE
UI idea

### ISSUE THREAD

**Issue by RowanDDR** [10se1ucgo/DisableWinTracking#61]
Instead of checkboxes, why not make each setting a toggle, so that end users can clearly see which items have already been disabled, or are yet to be disabled. I realise this may require a lot of extra code in order to probe the condition(s) behind each setting, to see if they are already applied, but anyway I just wanted to put the idea out there and see what the author thinks.

Because at the moment, its not clear to the end user if running the same settings twice (i.e. when starting a new version of the program) will cause a build up of problems i.e. is the firewall or hosts file filling up with duplicate conditions if I run the program over and over? etc

Anyway, I appreciate that this program is perhaps still in its infancy to a degree, as all the evil things Win10 does still seem to be emerging. So perhaps it would be more logical to implement this when the program has reached a more mature stage. If at all.

**Comment by 10se1ucgo** [comment]
I have a clutter control function built in that checks if the user has already applied the Firewall/Hosts modification and prevents it from re-applying it without reverting it first, so that should be fine. As for your other idea, I don't see it happening in the foreseeable future but who knows, maybe.

**Comment by Ruined1** [comment]
@RowanDDR I could see how that would be a nice feature, but considering the amount of work to put in eye-candy instead of adding new features seems a later-game idea. Definitely keep it in mind if I run out of other tasks or just get cramped and want to work on something fun, but for now, with the clutter control @10se1ucgo did such an awesome job on, if you aren't sure which you already have, it's not a big deal. Just check the ones you want and get privacy. If you already have one or two, no big deal, if you don't, now you do. :smile:
