### ISSUE TITLE
"Access is denied" regarding Windows Defender

### ISSUE THREAD

**Issue by s0rg0** [10se1ucgo/DisableWinTracking#88]
Each time I run the application (yes, as an administrator) with the Defender/Wifisense box ticked, I encounter the following two errors:

"02:19:57 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 578, in modifyregistry
WindowsError: [Error 5] Access is denied

02:19:57 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 578, in modifyregistry
WindowsError: [Error 5] Access is denied"

**Comment by 10se1ucgo** [comment]
Known issue, windows is protecting defender. Looking for a workaround.

**Comment by s0rg0** [comment]
Thanks, sorry for the duplicate issue.

**Comment by 10se1ucgo** [comment]
@s0rg0 It's fine, we need an open issue anyways.

**Comment by Ruined1** [comment]
@10se1ucgo even with an open issue there will still be duplicates :laughing:

**Comment by knotverygood** [comment]
Getting the same issue as OP running version 2.5:

15:33:17 ERROR: Registry: Unable to modify Windows Defender Spynet key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

15:33:17 ERROR: Registry: Unable to modify Windows Defender Sample Submission key.
Traceback (most recent call last):
  File "<string>", line 575, in modifyregistry
WindowsError: [Error 5] Access is denied

**Comment by 10se1ucgo** [comment]
Yes yes, everyone does, it's confirmed. However I haven't looked into a fix yet as I'm doing some other things.

**Comment by knotverygood** [comment]
Thanks 10se1ucgo. No pressure, just the fate of the world depending on you =). But seriously, great job with this. I tried disable Windows Defender first and then running it and it was a no go. I'll dive into the source when I get home from work and see what I can find.

**Comment by Ruined1** [comment]
@knotverygood the problem is not the code, it is not a bug with DisableWinTracking... The issues is the ONLY account that has permissions to change those two registry keys is SYSTEM. So, even ADMINISTRATOR cannot change them. I've tried several work-arounds to circumvent this, both in powershell, and a frustrating amount of time wasted trying to take ownership of the keys for administrator, with no luck.

**Comment by 10se1ucgo** [comment]
Hmm, `sc stop WinDefend` before modifying the keys doesn't work?

**Comment by 10se1ucgo** [comment]
Okay, using Set-ACL might help us here.

**Comment by Ruined1** [comment]
@10se1ucgo already tried it, good luck

**Comment by knotverygood** [comment]
How about this?
 sc stop WinDefend

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{D8559EB9-20C0-410E-BEDA-7ED416AECC2A} ;
    Right on {D8559EB9-20C0-410E-BEDA-7ED416AECC2A}, Permissions ... then Advanced;
    Click Change Owner

**Comment by Ruined1** [comment]
@knotverygood yes that's perfectly viable (although you're looking at the wrong spot in the registry). We're trying to find a way to automate it from the program.

**Comment by knotverygood** [comment]
The registry has  {D8559EB9-20C0-410E-BEDA-7ED416AECC2A} set as "TrustedInstaller" as the "Owner". What is wrong with editing this in the registry? Would this not solve the problem?

**Comment by knotverygood** [comment]
Maybe... run this as TrustedInstaller instead of admin. Look here: https://github.com/jschicht/RunAsTI

**Comment by Ruined1** [comment]
@knotverygood unfortunately the author of that program has not posted a license, which makes his code open source, but not usable. Technically, legally, we can't even use the compiled EXE to do the intended function because, again, no license... I may simply try to implement this via python though, but that depends on the license attached to RunAsTI (hopefully there is one...)

**Comment by Ruined1** [comment]
@10se1ucgo @knotverygood @s0rg0 As you can see here:
![](http://i.imgur.com/3qTdJHs.png)

Even the highest account cannot change these values, that is, the SYSTEM account. You can't tell from the screenshot, but I also copied the token from the trustedinstaller to run this as well... Both SYSTEM and TRUSTEDINSTALLER have full permissions to access that key by default in a clean windows 10 install... I'm stumped.

**Comment by knotverygood** [comment]
@Ruined1 Yes, you are right. What you have to do is actually change the owner. You cannot run it at system or TI regardless if it is already owned by system or TI. You must make it so the Administrator is the owner.

**Comment by 10se1ucgo** [comment]
Yep. I can do it manually but it's a bit confusing to do it from PowerShell. I'll look into giving it TrustedInstaller privilege.

**Comment by knotverygood** [comment]
I am pretty sure I had read that this is a security feature of Windows. They only way to do this is by changing who the owner is, rather than running it as TI or System.

**Comment by Ruined1** [comment]
@10se1ucgo, as I stated;
>Yep. I can do it manually but it's a bit confusing to do it from PowerShell. I'll look into giving it TrustedInstaller privilege.

This is exactly what I did, with no success.

I do wish you luck though.

**Comment by 10se1ucgo** [comment]
@Ruined1 He's added the MIT license, we should be good to go.

**Comment by W4RH4WK** [comment]
If I recall correctly, I have been stumbling over the same issue. Since I am using PowerShell I have created function which changes the ownership and permission of registry keys so that the administrator can write to them, see [Takeown-Registry](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/lib/take-own.psm1#L1-L33)

The problem is, that for this to work you have to do some kind of privileges elevation (which requires you to be administrator) to change the ACLs of the keys. This part is not created by myself and written in C#, see [Elevate-Privileges](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/lib/take-own.psm1#L61-L106).

The latter function gets called this way at the start of one of my scripts:

```ps1
echo "Elevating priviledges for this process"
do {} until (Elevate-Privileges SeTakeOwnershipPrivilege)
```

While this may not directly solve this issue it may help out.

**Comment by Ruined1** [comment]
@10se1ucgo I know, if you look at the issue tracker for that github, I asked him to and he did lol I was surprised since it hadn't been touched in a long long time :open_mouth:

**Comment by thejynxed** [comment]
With Win8-Win10 Trusted Installer now takes primacy over System or Administrator when it comes to dealing with files, folders & registry keys belonging to the OS itself. Windows Resource Protection is a thing.

**Comment by stopthespying** [comment]
Microsoft is locking us out and even if like me you write some code to give the administrator rights to WinDefend keys then you still cannot change the startup of the service.

Yes sure Microsoft can ban on about security when i want to delete details about a pen-stick that's saved to the registry and cannot gain access to delete it because windows is part of the NSA and it's all about spying on the users. 

The answer to Reg-Clean programs is to boil the fog and just keep removing our rights one bit at a time and the same is happening to the file system

**Comment by WindowsWorkaround101** [comment]
I've found a way to *COMPLETELY REMOVE WINDOWS DEFENDER* from the computer!

**Comment by Ruined1** [comment]
Unfortunately, I was never able to solve this. It's a limitation of windows itself, or I haven't located a viable work-around...

**Comment by wdfix** [comment]
If you're using SCCM
-Suspend BitLocker If enabled
-Mount a SCCM boot media iso Boot into WinPE
-Load Hive D:\Windows\System32\config\SYSTEM (which ever your OS partition)
-Change SYSTEM\ControlSet001\Services\WinDefend -> Start to 2
-Unload hive
-Reboot into full OS
